import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { SlLogout } from "react-icons/sl";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-black text-white p-4 font-bold flex items-center gap-2 justify-end fixed w-full">
          Clara Silva{" "}
          <span className="text-red-400 cursor-pointer">
            <SlLogout />
          </span>
        </nav>
        {children}
      </body>
    </html>
  );
}
