import type { Metadata } from "next";
import { Inter, Playfair_Display, Rubik } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const fontLogo = Rubik({
  subsets: ["latin"],
});
import { SlLogout } from "react-icons/sl";
import { cn } from "@/lib/utils";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" border-b border-gray-400 p-4   flex items-center gap-2 justify-between fixed w-full">
          <div>
            <h2 className={cn(fontLogo.className)}>
              <span className="text-red-800">MyDrop</span> Photos
            </h2>
          </div>
          <div className="flex items-center gap-4">
            Clara Silva{" "}
            <span className="cursor-pointer">
              <SlLogout size="20" />
            </span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
